In [1]:
import etl
import pandas as pd

test_files = [
    './Data/SEBRA-09042026.xlsx',
    './Data/SEBRA-15052026.xlsx',
    './Data/SEBRA-27052026.xlsx',
    './Data/SEBRA-28052026.xlsx',
]

In [9]:
r = etl.parse_sebra_payments_xlsx('./Data/SEBRA-09042026.xlsx')

INFO:etl:Skipping column header row in summary, row=['Код', 'Описание', nan, 'Сума']
INFO:etl:Skipping descriptive row in summary: I. ПЛАЩАНИЯ ОТ БЮДЖЕТА, ИЗВЪРШЕНИ ЧРЕЗ СЕБРА, ПО ПЪРВОСТЕПЕННИ СИСТЕМИ, row=['I. ПЛАЩАНИЯ ОТ БЮДЖЕТА, ИЗВЪРШЕНИ ЧРЕЗ СЕБРА, ПО ПЪРВОСТЕПЕННИ СИСТЕМИ', nan, nan, nan]
INFO:etl:Skipping descriptive row between sections: ПЛАЩАНИЯ ОТ БЮДЖЕТА, ИЗВЪРШЕНИ ЧРЕЗ СЕБРА, ПО ПЪРВОСТЕПЕННИ СИСТЕМИ, row=['ПЛАЩАНИЯ ОТ БЮДЖЕТА, ИЗВЪРШЕНИ ЧРЕЗ СЕБРА, ПО ПЪРВОСТЕПЕННИ СИСТЕМИ', nan, nan, nan]
INFO:etl:Skipping column header row in org section, row=['Код', 'Описание', nan, 'Сума']
INFO:etl:Skipping column header row in org section, row=['Код', 'Описание', nan, 'Сума']
INFO:etl:Skipping column header row in org section, row=['Код', 'Описание', nan, 'Сума']
INFO:etl:Skipping column header row in org section, row=['Код', 'Описание', nan, 'Сума']
INFO:etl:Skipping column header row in org section, row=['Код', 'Описание', nan, 'Сума']
INFO:etl:Skipping column header row in org section, row=['Код', 'Описание', nan, 'Сума']
INFO:etl:Skipping column header row in org section, row=['Код', 'Описание', nan, 'Сума']
INFO:etl:Skipping column header row in org section, row=['Код', 'Описание', nan, 'Сума']
INFO:etl:Skipping column header row in org section, row=['Код', 'Описание', nan, 'Сума']
INFO:etl:Skipping column header row in org section, row=['Код', 'Описание', nan, 'Сума']
INFO:etl:Skipping column header row in org section, row=['Код', 'Описание', nan, 'Сума']
INFO:etl:Skipping column header row in org section, row=['Код', 'Описание', nan, 'Сума']
INFO:etl:Skipping column header row in org section, row=['Код', 'Описание', nan, 'Сума']
INFO:etl:Skipping column header row in org section, row=['Код', 'Описание', nan, 'Сума']
INFO:etl:Skipping column header row in org section, row=['Код', 'Описание', nan, 'Сума']
INFO:etl:Skipping column header row in org section, row=['Код', 'Описание', nan, 'Сума']
INFO:etl:Skipping column header row in org section, row=['Код', 'Описание', nan, 'Сума']
INFO:etl:Skipping column header row in org section, row=['Код', 'Описание', nan, 'Сума']
INFO:etl:Skipping column header row in org section, row=['Код', 'Описание', nan, 'Сума']
INFO:etl:Skipping column header row in org section, row=['Код', 'Описание', nan, 'Сума']
INFO:etl:Skipping column header row in org section, row=['Код', 'Описание', nan, 'Сума']
INFO:etl:Skipping column header row in org section, row=['Код', 'Описание', nan, 'Сума']
INFO:etl:Skipping column header row in org section, row=['Код', 'Описание', nan, 'Сума']
INFO:etl:Skipping column header row in org section, row=['Код', 'Описание', nan, 'Сума']
INFO:etl:Skipping column header row in org section, row=['Код', 'Описание', nan, 'Сума']
INFO:etl:Skipping column header row in org section, row=['Код', 'Описание', nan, 'Сума']
INFO:etl:Skipping column header row in org section, row=['Код', 'Описание', nan, 'Сума']
INFO:etl:Skipping column header row in org section, row=['Код', 'Описание', nan, 'Сума']
INFO:etl:Skipping column header row in org section, row=['Код', 'Описание', nan, 'Сума']
INFO:etl:Skipping column header row in org section, row=['Код', 'Описание', nan, 'Сума']
INFO:etl:Skipping column header row in org section, row=['Код', 'Описание', nan, 'Сума']
INFO:etl:Skipping column header row in org section, row=['Код', 'Описание', nan, 'Сума']
INFO:etl:Skipping column header row in org section, row=['Код', 'Описание', nan, 'Сума']
INFO:etl:Skipping column header row in org section, row=['Код', 'Описание', nan, 'Сума']
INFO:etl:Skipping column header row in org section, row=['Код', 'Описание', nan, 'Сума']
INFO:etl:Skipping column header row in org section, row=['Код', 'Описание', nan, 'Сума']
INFO:etl:Skipping column header row in org section, row=['Код', 'Описание', nan, 'Сума']
INFO:etl:Skipping column header row in org section, row=['Код', 'Описание', nan, 'Сума']
INFO:etl:Skipping column header row in org section, row=['Код', 'Описание', nan, 'Сума']
INFO:etl:Skipping column header row in org section, row=['Код', 'Описание', nan, 'Сума']
INFO:etl:Skipping column header row in org section, row=['Код', 'Описание', nan, 'Сума']
INFO:etl:Skipping column header row in org section, row=['Код', 'Описание', nan, 'Сума']
INFO:etl:Skipping column header row in org section, row=['Код', 'Описание', nan, 'Сума']
INFO:etl:Skipping column header row in org section, row=['Код', 'Описание', nan, 'Сума']
INFO:etl:Skipping column header row in org section, row=['Код', 'Описание', nan, 'Сума']
INFO:etl:Skipping column header row in org section, row=['Код', 'Описание', nan, 'Сума']
INFO:etl:Skipping column header row in org section, row=['Код', 'Описание', nan, 'Сума']
INFO:etl:Skipping column header row in org section, row=['Код', 'Описание', nan, 'Сума']
INFO:etl:Skipping column header row in org section, row=['Код', 'Описание', nan, 'Сума']
INFO:etl:Skipping column header row in org section, row=['Код', 'Описание', nan, 'Сума']
INFO:etl:Skipping column header row in org section, row=['Код', 'Описание', nan, 'Сума']
INFO:etl:Skipping column header row in org section, row=['Код', 'Описание', nan, 'Сума']
INFO:etl:Skipping column header row in org section, row=['Код', 'Описание', nan, 'Сума']
INFO:etl:Skipping column header row in org section, row=['Код', 'Описание', nan, 'Сума']
INFO:etl:Skipping column header row in org section, row=['Код', 'Описание', nan, 'Сума']
INFO:etl:Skipping column header row in org section, row=['Код', 'Описание', nan, 'Сума']
INFO:etl:Skipping column header row in org section, row=['Код', 'Описание', nan, 'Сума']
INFO:etl:Skipping column header row in org section, row=['Код', 'Описание', nan, 'Сума']
INFO:etl:Skipping column header row in org section, row=['Код', 'Описание', nan, 'Сума']
INFO:etl:Skipping column header row in org section, row=['Код', 'Описание', nan, 'Сума']
INFO:etl:Skipping column header row in org section, row=['Код', 'Описание', nan, 'Сума']
INFO:etl:Skipping column header row in org section, row=['Код', 'Описание', nan, 'Сума']
INFO:etl:Skipping column header row in org section, row=['Код', 'Описание', nan, 'Сума']
INFO:etl:Skipping column header row in org section, row=['Код', 'Описание', nan, 'Сума']
INFO:etl:Skipping column header row in org section, row=['Код', 'Описание', nan, 'Сума']
INFO:etl:Skipping column header row in org section, row=[nan, 'Описание', nan, 'Сума']
INFO:etl:Skipping column header row in org section, row=[nan, 'Описание', nan, 'Сума']

In [4]:
r.summary.data

,start_date,end_date,operation_code,operation_description,currency,amount
0,09.04.2026,09.04.2026,01,"Заплати, възнаграждения и други плащания за пе...",EUR,6364717.34
1,09.04.2026,09.04.2026,02,Удържани данъци и осигурителни вноски от запла...,EUR,16253.45
2,09.04.2026,09.04.2026,03,Плащания за други удръжки от възнаграждения за...,EUR,22368.44
3,09.04.2026,09.04.2026,05,Осигурителни вноски за сметка на осигурителя,EUR,12253.26
4,09.04.2026,09.04.2026,10,Издръжка,EUR,14594595.12
5,09.04.2026,09.04.2026,18,Други разходи,EUR,695783.96
6,09.04.2026,09.04.2026,20,Разходи за лихви,EUR,15.13
7,09.04.2026,09.04.2026,30,Текущи субсидии за предприятия,EUR,4482514.54
8,09.04.2026,09.04.2026,40,"Стипендии, пенсии, помощи и текущи трансфери з...",EUR,111460330.38
9,09.04.2026,09.04.2026,50,"Плащания за дълготрайни активи, основен ремонт...",EUR,6291944.98
10,09.04.2026,09.04.2026,60,Трансфери за бюджетни и извънбюджетни сметки,EUR,9913308.45
11,09.04.2026,09.04.2026,88,Средства на разпореждане,EUR,531119.66
12,09.04.2026,09.04.2026,89,Друго финансиране,EUR,13621749.29
13,09.04.2026,09.04.2026,90,Възстановени приходи,EUR,2870412.18
14,09.04.2026,09.04.2026,91,Теглене на BGN в брой,EUR,7000
15,09.04.2026,09.04.2026,93,"Закупуване на валута в брой, по сметка и за ди...",EUR,885098.26
16,09.04.2026,09.04.2026,96,Преводи по нареждане на титуляра с други плате...,EUR,4026672.14
17,09.04.2026,09.04.2026,98,Други операции в БНБ,EUR,-92111.33
18,09.04.2026,09.04.2026,2974e36,Трансфери за местни дейности за общини,EUR,123037.31
19,09.04.2026,09.04.2026,55d283b,Обща субсидия за финансиране на делегираните о...,EUR,3489209
20,09.04.2026,09.04.2026,d8b5c4b,Трансфери за други целеви разходи за общини,EUR,682181.80

In [44]:


from decimal import getcontext, Decimal
import pandas as pd

getcontext().prec = 15

def decimal_sum(s: pd.Series) -> Decimal:
    s = Decimal('0.0')
    for i in amounts:
        s = s + i
    return s


amounts = r.summary.data['amount']
decimal_sum(amounts)

Decimal('179998453.36')

In [46]:
org_total = Decimal('0')
for o in r.org_sections:
    org_total += o.total_sum

org_total

Decimal('179998453.36')

In [5]:
def load_excel(f: str) -> pd.DataFrame:
    data = pd.read_excel(f)
    data = data.dropna(how='all')
    return data

In [3]:
sebra_data = etl.parse_sebra_payments_xlsx(test_files[0])
dir(sebra_data)

INFO:etl:[summary section] Skipping column header row in summary, row=['Код', 'Описание', nan, 'Сума']
INFO:etl:[summary section] Skipping descriptive row in summary: I. ПЛАЩАНИЯ ОТ БЮДЖЕТА, ИЗВЪРШЕНИ ЧРЕЗ СЕБРА, ПО ПЪРВОСТЕПЕННИ СИСТЕМИ, row=['I. ПЛАЩАНИЯ ОТ БЮДЖЕТА, ИЗВЪРШЕНИ ЧРЕЗ СЕБРА, ПО ПЪРВОСТЕПЕННИ СИСТЕМИ', nan, nan, nan]
INFO:etl:[org section] Skipping descriptive row between sections: ПЛАЩАНИЯ ОТ БЮДЖЕТА, ИЗВЪРШЕНИ ЧРЕЗ СЕБРА, ПО ПЪРВОСТЕПЕННИ СИСТЕМИ, row=['ПЛАЩАНИЯ ОТ БЮДЖЕТА, ИЗВЪРШЕНИ ЧРЕЗ СЕБРА, ПО ПЪРВОСТЕПЕННИ СИСТЕМИ', nan, nan, nan]
INFO:etl:[org section] Skipping column header row in org section, row=['Код', 'Описание', nan, 'Сума']
INFO:etl:[org section] Skipping column header row in org section, row=['Код', 'Описание', nan, 'Сума']
INFO:etl:[org section] Skipping column header row in org section, row=['Код', 'Описание', nan, 'Сума']
INFO:etl:[org section] Skipping column header row in org section, row=['Код', 'Описание', nan, 'Сума']
INFO:etl:[org section] Skipping column header row in org section, row=['Код', 'Описание', nan, 'Сума']
INFO:etl:[org section] Skipping column header row in org section, row=['Код', 'Описание', nan, 'Сума']
INFO:etl:[org section] Skipping column header row in org section, row=['Код', 'Описание', nan, 'Сума']
INFO:etl:[org section] Skipping column header row in org section, row=['Код', 'Описание', nan, 'Сума']
INFO:etl:[org section] Skipping column header row in org section, row=['Код', 'Описание', nan, 'Сума']
INFO:etl:[org section] Skipping column header row in org section, row=['Код', 'Описание', nan, 'Сума']
INFO:etl:[org section] Skipping column header row in org section, row=['Код', 'Описание', nan, 'Сума']
INFO:etl:[org section] Skipping column header row in org section, row=['Код', 'Описание', nan, 'Сума']
INFO:etl:[org section] Skipping column header row in org section, row=['Код', 'Описание', nan, 'Сума']
INFO:etl:[org section] Skipping column header row in org section, row=['Код', 'Описание', nan, 'Сума']
INFO:etl:[org section] Skipping column header row in org section, row=['Код', 'Описание', nan, 'Сума']
INFO:etl:[org section] Skipping column header row in org section, row=['Код', 'Описание', nan, 'Сума']
INFO:etl:[org section] Skipping column header row in org section, row=['Код', 'Описание', nan, 'Сума']
INFO:etl:[org section] Skipping column header row in org section, row=['Код', 'Описание', nan, 'Сума']
INFO:etl:[org section] Skipping column header row in org section, row=['Код', 'Описание', nan, 'Сума']
INFO:etl:[org section] Skipping column header row in org section, row=['Код', 'Описание', nan, 'Сума']
INFO:etl:[org section] Skipping column header row in org section, row=['Код', 'Описание', nan, 'Сума']
INFO:etl:[org section] Skipping column header row in org section, row=['Код', 'Описание', nan, 'Сума']
INFO:etl:[org section] Skipping column header row in org section, row=['Код', 'Описание', nan, 'Сума']
INFO:etl:[org section] Skipping column header row in org section, row=['Код', 'Описание', nan, 'Сума']
INFO:etl:[org section] Skipping column header row in org section, row=['Код', 'Описание', nan, 'Сума']
INFO:etl:[org section] Skipping column header row in org section, row=['Код', 'Описание', nan, 'Сума']
INFO:etl:[org section] Skipping column header row in org section, row=['Код', 'Описание', nan, 'Сума']
INFO:etl:[org section] Skipping column header row in org section, row=['Код', 'Описание', nan, 'Сума']
INFO:etl:[org section] Skipping column header row in org section, row=['Код', 'Описание', nan, 'Сума']
INFO:etl:[org section] Skipping column header row in org section, row=['Код', 'Описание', nan, 'Сума']
INFO:etl:[org section] Skipping column header row in org section, row=['Код', 'Описание', nan, 'Сума']
INFO:etl:[org section] Skipping column header row in org section, row=['Код', 'Описание', nan, 'Сума']
INFO:etl:[org section] Skipping column header row in org section, row=['Код', 'Описание', nan, 'Сума']
INFO:etl:[org section] Skipping column header row in org section, row=['Код', 'Описание', nan, 'Сума']
INFO:etl:[org section] Skipping column header row in org section, row=['Код', 'Описание', nan, 'Сума']
INFO:etl:[org section] Skipping column header row in org section, row=['Код', 'Описание', nan, 'Сума']
INFO:etl:[org section] Skipping column header row in org section, row=['Код', 'Описание', nan, 'Сума']
INFO:etl:[org section] Skipping column header row in org section, row=['Код', 'Описание', nan, 'Сума']
INFO:etl:[org section] Skipping column header row in org section, row=['Код', 'Описание', nan, 'Сума']
INFO:etl:[org section] Skipping column header row in org section, row=['Код', 'Описание', nan, 'Сума']
INFO:etl:[org section] Skipping column header row in org section, row=['Код', 'Описание', nan, 'Сума']
INFO:etl:[org section] Skipping column header row in org section, row=['Код', 'Описание', nan, 'Сума']
INFO:etl:[org section] Skipping column header row in org section, row=['Код', 'Описание', nan, 'Сума']
INFO:etl:[org section] Skipping column header row in org section, row=['Код', 'Описание', nan, 'Сума']
INFO:etl:[org section] Skipping column header row in org section, row=['Код', 'Описание', nan, 'Сума']
INFO:etl:[org section] Skipping column header row in org section, row=['Код', 'Описание', nan, 'Сума']
INFO:etl:[org section] Skipping column header row in org section, row=['Код', 'Описание', nan, 'Сума']
INFO:etl:[org section] Skipping column header row in org section, row=['Код', 'Описание', nan, 'Сума']
INFO:etl:[org section] Skipping column header row in org section, row=['Код', 'Описание', nan, 'Сума']
INFO:etl:[org section] Skipping column header row in org section, row=['Код', 'Описание', nan, 'Сума']
INFO:etl:[org section] Skipping column header row in org section, row=['Код', 'Описание', nan, 'Сума']
INFO:etl:[org section] Skipping column header row in org section, row=['Код', 'Описание', nan, 'Сума']
INFO:etl:[org section] Skipping column header row in org section, row=['Код', 'Описание', nan, 'Сума']
INFO:etl:[org section] Skipping column header row in org section, row=['Код', 'Описание', nan, 'Сума']
INFO:etl:[org section] Skipping column header row in org section, row=['Код', 'Описание', nan, 'Сума']
INFO:etl:[org section] Skipping column header row in org section, row=['Код', 'Описание', nan, 'Сума']
INFO:etl:[org section] Skipping column header row in org section, row=['Код', 'Описание', nan, 'Сума']
INFO:etl:[org section] Skipping column header row in org section, row=['Код', 'Описание', nan, 'Сума']
INFO:etl:[org section] Skipping column header row in org section, row=['Код', 'Описание', nan, 'Сума']
INFO:etl:[org section] Skipping column header row in org section, row=['Код', 'Описание', nan, 'Сума']
INFO:etl:[org section] Skipping column header row in org section, row=['Код', 'Описание', nan, 'Сума']
INFO:etl:[org section] Skipping column header row in org section, row=['Код', 'Описание', nan, 'Сума']
INFO:etl:[org section] Skipping column header row in org section, row=['Код', 'Описание', nan, 'Сума']
INFO:etl:[org section] Skipping column header row in org section, row=['Код', 'Описание', nan, 'Сума']
INFO:etl:[org section] Skipping column header row in org section, row=['Код', 'Описание', nan, 'Сума']
INFO:etl:[org section] Skipping column header row in org section, row=[nan, 'Описание', nan, 'Сума']
INFO:etl:[org section] Skipping column header row in org section, row=[nan, 'Описание', nan, 'Сума']

['__annotations__',
 '__class__',
 '__dataclass_fields__',
 '__dataclass_params__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__firstlineno__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__match_args__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__replace__',
 '__repr__',
 '__setattr__',
 '__sizeof__',
 '__static_attributes__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 'filename',
 'org_sections',
 'summary',
 'validate_total_sum']

In [14]:
import etl
import importlib
importlib.reload(etl)

test_files = [
    './Data/SEBRA-09042026.xlsx',
    './Data/SEBRA-15052026.xlsx',
    './Data/SEBRA-27052026.xlsx',
    './Data/SEBRA-28052026.xlsx',
]

sebra_datas = [
    etl.parse_sebra_payments_xlsx(tf) for tf in test_files
]

test_results = [
    sd.validate_total_sum() for sd in sebra_datas
]

test_results

INFO:etl:parsing SEBRA-09042026.xlsx
INFO:etl:[summary section] Skipping column header row in summary, row=['Код', 'Описание', nan, 'Сума']
INFO:etl:[summary section] Skipping descriptive row in summary: I. ПЛАЩАНИЯ ОТ БЮДЖЕТА, ИЗВЪРШЕНИ ЧРЕЗ СЕБРА, ПО ПЪРВОСТЕПЕННИ СИСТЕМИ, row=['I. ПЛАЩАНИЯ ОТ БЮДЖЕТА, ИЗВЪРШЕНИ ЧРЕЗ СЕБРА, ПО ПЪРВОСТЕПЕННИ СИСТЕМИ', nan, nan, nan]
INFO:etl:[org section] Skipping descriptive row between sections: ПЛАЩАНИЯ ОТ БЮДЖЕТА, ИЗВЪРШЕНИ ЧРЕЗ СЕБРА, ПО ПЪРВОСТЕПЕННИ СИСТЕМИ, row=['ПЛАЩАНИЯ ОТ БЮДЖЕТА, ИЗВЪРШЕНИ ЧРЕЗ СЕБРА, ПО ПЪРВОСТЕПЕННИ СИСТЕМИ', nan, nan, nan]
INFO:etl:[org section] Skipping column header row in org section, row=['Код', 'Описание', nan, 'Сума']
INFO:etl:[org section] Skipping column header row in org section, row=['Код', 'Описание', nan, 'Сума']
INFO:etl:[org section] Skipping column header row in org section, row=['Код', 'Описание', nan, 'Сума']
INFO:etl:[org section] Skipping column header row in org section, row=['Код', 'Описание', nan, 'Сума']
INFO:etl:[org section] Skipping column header row in org section, row=['Код', 'Описание', nan, 'Сума']
INFO:etl:[org section] Skipping column header row in org section, row=['Код', 'Описание', nan, 'Сума']
INFO:etl:[org section] Skipping column header row in org section, row=['Код', 'Описание', nan, 'Сума']
INFO:etl:[org section] Skipping column header row in org section, row=['Код', 'Описание', nan, 'Сума']
INFO:etl:[org section] Skipping column header row in org section, row=['Код', 'Описание', nan, 'Сума']
INFO:etl:[org section] Skipping column header row in org section, row=['Код', 'Описание', nan, 'Сума']
INFO:etl:[org section] Skipping column header row in org section, row=['Код', 'Описание', nan, 'Сума']
INFO:etl:[org section] Skipping column header row in org section, row=['Код', 'Описание', nan, 'Сума']
INFO:etl:[org section] Skipping column header row in org section, row=['Код', 'Описание', nan, 'Сума']
INFO:etl:[org section] Skipping column header row in org section, row=['Код', 'Описание', nan, 'Сума']
INFO:etl:[org section] Skipping column header row in org section, row=['Код', 'Описание', nan, 'Сума']
INFO:etl:[org section] Skipping column header row in org section, row=['Код', 'Описание', nan, 'Сума']
INFO:etl:[org section] Skipping column header row in org section, row=['Код', 'Описание', nan, 'Сума']
INFO:etl:[org section] Skipping column header row in org section, row=['Код', 'Описание', nan, 'Сума']
INFO:etl:[org section] Skipping column header row in org section, row=['Код', 'Описание', nan, 'Сума']
INFO:etl:[org section] Skipping column header row in org section, row=['Код', 'Описание', nan, 'Сума']
INFO:etl:[org section] Skipping column header row in org section, row=['Код', 'Описание', nan, 'Сума']
INFO:etl:[org section] Skipping column header row in org section, row=['Код', 'Описание', nan, 'Сума']
INFO:etl:[org section] Skipping column header row in org section, row=['Код', 'Описание', nan, 'Сума']
INFO:etl:[org section] Skipping column header row in org section, row=['Код', 'Описание', nan, 'Сума']
INFO:etl:[org section] Skipping column header row in org section, row=['Код', 'Описание', nan, 'Сума']
INFO:etl:[org section] Skipping column header row in org section, row=['Код', 'Описание', nan, 'Сума']
INFO:etl:[org section] Skipping column header row in org section, row=['Код', 'Описание', nan, 'Сума']
INFO:etl:[org section] Skipping column header row in org section, row=['Код', 'Описание', nan, 'Сума']
INFO:etl:[org section] Skipping column header row in org section, row=['Код', 'Описание', nan, 'Сума']
INFO:etl:[org section] Skipping column header row in org section, row=['Код', 'Описание', nan, 'Сума']
INFO:etl:[org section] Skipping column header row in org section, row=['Код', 'Описание', nan, 'Сума']
INFO:etl:[org section] Skipping column header row in org section, row=['Код', 'Описание', nan, 'Сума']
INFO:etl:[org section] Skipping column header row in org section, row=['Код', 'Описание', nan, 'Сума']
INFO:etl:[org section] Skipping column header row in org section, row=['Код', 'Описание', nan, 'Сума']
INFO:etl:[org section] Skipping column header row in org section, row=['Код', 'Описание', nan, 'Сума']
INFO:etl:[org section] Skipping column header row in org section, row=['Код', 'Описание', nan, 'Сума']
INFO:etl:[org section] Skipping column header row in org section, row=['Код', 'Описание', nan, 'Сума']
INFO:etl:[org section] Skipping column header row in org section, row=['Код', 'Описание', nan, 'Сума']
INFO:etl:[org section] Skipping column header row in org section, row=['Код', 'Описание', nan, 'Сума']
INFO:etl:[org section] Skipping column header row in org section, row=['Код', 'Описание', nan, 'Сума']
INFO:etl:[org section] Skipping column header row in org section, row=['Код', 'Описание', nan, 'Сума']
INFO:etl:[org section] Skipping column header row in org section, row=['Код', 'Описание', nan, 'Сума']
INFO:etl:[org section] Skipping column header row in org section, row=['Код', 'Описание', nan, 'Сума']
INFO:etl:[org section] Skipping column header row in org section, row=['Код', 'Описание', nan, 'Сума']
INFO:etl:[org section] Skipping column header row in org section, row=['Код', 'Описание', nan, 'Сума']
INFO:etl:[org section] Skipping column header row in org section, row=['Код', 'Описание', nan, 'Сума']
INFO:etl:[org section] Skipping column header row in org section, row=['Код', 'Описание', nan, 'Сума']
INFO:etl:[org section] Skipping column header row in org section, row=['Код', 'Описание', nan, 'Сума']
INFO:etl:[org section] Skipping column header row in org section, row=['Код', 'Описание', nan, 'Сума']
INFO:etl:[org section] Skipping column header row in org section, row=['Код', 'Описание', nan, 'Сума']
INFO:etl:[org section] Skipping column header row in org section, row=['Код', 'Описание', nan, 'Сума']
INFO:etl:[org section] Skipping column header row in org section, row=['Код', 'Описание', nan, 'Сума']
INFO:etl:[org section] Skipping column header row in org section, row=['Код', 'Описание', nan, 'Сума']
INFO:etl:[org section] Skipping column header row in org section, row=['Код', 'Описание', nan, 'Сума']
INFO:etl:[org section] Skipping column header row in org section, row=['Код', 'Описание', nan, 'Сума']
INFO:etl:[org section] Skipping column header row in org section, row=['Код', 'Описание', nan, 'Сума']
INFO:etl:[org section] Skipping column header row in org section, row=['Код', 'Описание', nan, 'Сума']
INFO:etl:[org section] Skipping column header row in org section, row=['Код', 'Описание', nan, 'Сума']
INFO:etl:[org section] Skipping column header row in org section, row=['Код', 'Описание', nan, 'Сума']
INFO:etl:[org section] Skipping column header row in org section, row=['Код', 'Описание', nan, 'Сума']
INFO:etl:[org section] Skipping column header row in org section, row=['Код', 'Описание', nan, 'Сума']
INFO:etl:[org section] Skipping column header row in org section, row=['Код', 'Описание', nan, 'Сума']
INFO:etl:[org section] Skipping column header row in org section, row=['Код', 'Описание', nan, 'Сума']
INFO:etl:[org section] Skipping column header row in org section, row=['Код', 'Описание', nan, 'Сума']
INFO:etl:[org section] Skipping column header row in org section, row=['Код', 'Описание', nan, 'Сума']
INFO:etl:[org section] Skipping column header row in org section, row=[nan, 'Описание', nan, 'Сума']
INFO:etl:[org section] Skipping column header row in org section, row=[nan, 'Описание', nan, 'Сума']
INFO:etl:parsing SEBRA-15052026.xlsx
INFO:etl:[summary section] Skipping column header row in summary, row=['Код', 'Описание', nan, 'Сума']
INFO:etl:[summary section] Skipping descriptive row in summary: I. ПЛАЩАНИЯ ОТ БЮДЖЕТА, ИЗВЪРШЕНИ ЧРЕЗ СЕБРА, ПО ПЪРВОСТЕПЕННИ СИСТЕМИ, row=['I. ПЛАЩАНИЯ ОТ БЮДЖЕТА, ИЗВЪРШЕНИ ЧРЕЗ СЕБРА, ПО ПЪРВОСТЕПЕННИ СИСТЕМИ', nan, nan, nan]
INFO:etl:[summary section] Skipping descriptive row in summary: II. ДРУГИ ИЗВЪРШЕНИ ПЛАЩАНИЯ В БНБ, row=['II. ДРУГИ ИЗВЪРШЕНИ ПЛАЩАНИЯ В БНБ', nan, nan, nan]
INFO:etl:[org section] Skipping descriptive row between sections: ПЛАЩАНИЯ ОТ БЮДЖЕТА, ИЗВЪРШЕНИ ЧРЕЗ СЕБРА, ПО ПЪРВОСТЕПЕННИ СИСТЕМИ, row=['ПЛАЩАНИЯ ОТ БЮДЖЕТА, ИЗВЪРШЕНИ ЧРЕЗ СЕБРА, ПО ПЪРВОСТЕПЕННИ СИСТЕМИ', nan, nan, nan]
INFO:etl:[org section] Skipping column header row in org section, row=['Код', 'Описание', nan, 'Сума']
INFO:etl:[org section] Skipping column header row in org section, row=['Код', 'Описание', nan, 'Сума']
INFO:etl:[org section] Skipping column header row in org section, row=['Код', 'Описание', nan, 'Сума']
INFO:etl:[org section] Skipping column header row in org section, row=['Код', 'Описание', nan, 'Сума']
INFO:etl:[org section] Skipping column header row in org section, row=['Код', 'Описание', nan, 'Сума']
INFO:etl:[org section] Skipping column header row in org section, row=['Код', 'Описание', nan, 'Сума']
INFO:etl:[org section] Skipping column header row in org section, row=['Код', 'Описание', nan, 'Сума']
INFO:etl:[org section] Skipping column header row in org section, row=['Код', 'Описание', nan, 'Сума']
INFO:etl:[org section] Skipping column header row in org section, row=['Код', 'Описание', nan, 'Сума']
INFO:etl:[org section] Skipping column header row in org section, row=['Код', 'Описание', nan, 'Сума']
INFO:etl:[org section] Skipping column header row in org section, row=['Код', 'Описание', nan, 'Сума']
INFO:etl:[org section] Skipping column header row in org section, row=['Код', 'Описание', nan, 'Сума']
INFO:etl:[org section] Skipping column header row in org section, row=['Код', 'Описание', nan, 'Сума']
INFO:etl:[org section] Skipping column header row in org section, row=['Код', 'Описание', nan, 'Сума']
INFO:etl:[org section] Skipping column header row in org section, row=['Код', 'Описание', nan, 'Сума']
INFO:etl:[org section] Skipping column header row in org section, row=['Код', 'Описание', nan, 'Сума']
INFO:etl:[org section] Skipping column header row in org section, row=['Код', 'Описание', nan, 'Сума']
INFO:etl:[org section] Skipping column header row in org section, row=['Код', 'Описание', nan, 'Сума']
INFO:etl:[org section] Skipping column header row in org section, row=['Код', 'Описание', nan, 'Сума']
INFO:etl:[org section] Skipping column header row in org section, row=['Код', 'Описание', nan, 'Сума']
INFO:etl:[org section] Skipping column header row in org section, row=['Код', 'Описание', nan, 'Сума']
INFO:etl:[org section] Skipping column header row in org section, row=['Код', 'Описание', nan, 'Сума']
INFO:etl:[org section] Skipping column header row in org section, row=['Код', 'Описание', nan, 'Сума']
INFO:etl:[org section] Skipping column header row in org section, row=['Код', 'Описание', nan, 'Сума']
INFO:etl:[org section] Skipping column header row in org section, row=['Код', 'Описание', nan, 'Сума']
INFO:etl:[org section] Skipping column header row in org section, row=['Код', 'Описание', nan, 'Сума']
INFO:etl:[org section] Skipping column header row in org section, row=['Код', 'Описание', nan, 'Сума']
INFO:etl:[org section] Skipping column header row in org section, row=['Код', 'Описание', nan, 'Сума']
INFO:etl:[org section] Skipping column header row in org section, row=['Код', 'Описание', nan, 'Сума']
INFO:etl:[org section] Skipping column header row in org section, row=['Код', 'Описание', nan, 'Сума']
INFO:etl:[org section] Skipping column header row in org section, row=['Код', 'Описание', nan, 'Сума']
INFO:etl:[org section] Skipping column header row in org section, row=['Код', 'Описание', nan, 'Сума']
INFO:etl:[org section] Skipping column header row in org section, row=['Код', 'Описание', nan, 'Сума']
INFO:etl:[org section] Skipping column header row in org section, row=['Код', 'Описание', nan, 'Сума']
INFO:etl:[org section] Skipping column header row in org section, row=['Код', 'Описание', nan, 'Сума']
INFO:etl:[org section] Skipping column header row in org section, row=['Код', 'Описание', nan, 'Сума']
INFO:etl:[org section] Skipping column header row in org section, row=['Код', 'Описание', nan, 'Сума']
INFO:etl:[org section] Skipping column header row in org section, row=['Код', 'Описание', nan, 'Сума']
INFO:etl:[org section] Skipping column header row in org section, row=['Код', 'Описание', nan, 'Сума']
INFO:etl:[org section] Skipping column header row in org section, row=['Код', 'Описание', nan, 'Сума']
INFO:etl:[org section] Skipping column header row in org section, row=['Код', 'Описание', nan, 'Сума']
INFO:etl:[org section] Skipping column header row in org section, row=['Код', 'Описание', nan, 'Сума']
INFO:etl:[org section] Skipping column header row in org section, row=['Код', 'Описание', nan, 'Сума']
INFO:etl:[org section] Skipping column header row in org section, row=['Код', 'Описание', nan, 'Сума']
INFO:etl:[org section] Skipping column header row in org section, row=['Код', 'Описание', nan, 'Сума']
INFO:etl:[org section] Skipping column header row in org section, row=['Код', 'Описание', nan, 'Сума']
INFO:etl:[org section] Skipping column header row in org section, row=['Код', 'Описание', nan, 'Сума']
INFO:etl:[org section] Skipping column header row in org section, row=['Код', 'Описание', nan, 'Сума']
INFO:etl:[org section] Skipping column header row in org section, row=['Код', 'Описание', nan, 'Сума']
INFO:etl:[org section] Skipping column header row in org section, row=['Код', 'Описание', nan, 'Сума']
INFO:etl:[org section] Skipping column header row in org section, row=['Код', 'Описание', nan, 'Сума']
INFO:etl:[org section] Skipping column header row in org section, row=['Код', 'Описание', nan, 'Сума']
INFO:etl:[org section] Skipping column header row in org section, row=['Код', 'Описание', nan, 'Сума']
INFO:etl:[org section] Skipping column header row in org section, row=['Код', 'Описание', nan, 'Сума']
INFO:etl:[org section] Skipping column header row in org section, row=['Код', 'Описание', nan, 'Сума']
INFO:etl:[org section] Skipping column header row in org section, row=['Код', 'Описание', nan, 'Сума']
INFO:etl:[org section] Skipping column header row in org section, row=['Код', 'Описание', nan, 'Сума']
INFO:etl:[org section] Skipping column header row in org section, row=['Код', 'Описание', nan, 'Сума']
INFO:etl:[org section] Skipping column header row in org section, row=['Код', 'Описание', nan, 'Сума']
INFO:etl:[org section] Skipping column header row in org section, row=['Код', 'Описание', nan, 'Сума']
INFO:etl:[org section] Skipping column header row in org section, row=['Код', 'Описание', nan, 'Сума']
INFO:etl:[org section] Skipping column header row in org section, row=['Код', 'Описание', nan, 'Сума']
INFO:etl:[org section] Skipping column header row in org section, row=['Код', 'Описание', nan, 'Сума']
INFO:etl:[org section] Skipping column header row in org section, row=['Код', 'Описание', nan, 'Сума']
INFO:etl:[org section] Skipping column header row in org section, row=['Код', 'Описание', nan, 'Сума']
INFO:etl:[org section] Skipping column header row in org section, row=['Код', 'Описание', nan, 'Сума']
INFO:etl:[org section] Skipping column header row in org section, row=['Код', 'Описание', nan, 'Сума']
INFO:etl:[org section] Skipping column header row in org section, row=['Код', 'Описание', nan, 'Сума']
INFO:etl:[org section] Skipping column header row in org section, row=['Код', 'Описание', nan, 'Сума']
INFO:etl:[org section] Skipping column header row in org section, row=['Код', 'Описание', nan, 'Сума']
INFO:etl:[org section] Skipping column header row in org section, row=[nan, 'Описание', nan, 'Сума']
INFO:etl:[org section] Skipping column header row in org section, row=[nan, 'Описание', nan, 'Сума']
INFO:etl:[org section] Skipping column header row in org section, row=[nan, 'Описание', nan, 'Сума']
INFO:etl:parsing SEBRA-27052026.xlsx
INFO:etl:[summary section] Skipping column header row in summary, row=['Код', 'Описание', nan, 'Сума']
INFO:etl:[summary section] Skipping descriptive row in summary: I. ПЛАЩАНИЯ ОТ БЮДЖЕТА, ИЗВЪРШЕНИ ЧРЕЗ СЕБРА, ПО ПЪРВОСТЕПЕННИ СИСТЕМИ, row=['I. ПЛАЩАНИЯ ОТ БЮДЖЕТА, ИЗВЪРШЕНИ ЧРЕЗ СЕБРА, ПО ПЪРВОСТЕПЕННИ СИСТЕМИ', nan, nan, nan]
INFO:etl:[summary section] Skipping descriptive row in summary: II. ДРУГИ ИЗВЪРШЕНИ ПЛАЩАНИЯ В БНБ, row=['II. ДРУГИ ИЗВЪРШЕНИ ПЛАЩАНИЯ В БНБ', nan, nan, nan]
INFO:etl:[org section] Skipping descriptive row between sections: ПЛАЩАНИЯ ОТ БЮДЖЕТА, ИЗВЪРШЕНИ ЧРЕЗ СЕБРА, ПО ПЪРВОСТЕПЕННИ СИСТЕМИ, row=['ПЛАЩАНИЯ ОТ БЮДЖЕТА, ИЗВЪРШЕНИ ЧРЕЗ СЕБРА, ПО ПЪРВОСТЕПЕННИ СИСТЕМИ', nan, nan, nan]
INFO:etl:[org section] Skipping column header row in org section, row=['Код', 'Описание', nan, 'Сума']
INFO:etl:[org section] Skipping column header row in org section, row=['Код', 'Описание', nan, 'Сума']
INFO:etl:[org section] Skipping column header row in org section, row=['Код', 'Описание', nan, 'Сума']
INFO:etl:[org section] Skipping column header row in org section, row=['Код', 'Описание', nan, 'Сума']
INFO:etl:[org section] Skipping column header row in org section, row=['Код', 'Описание', nan, 'Сума']
INFO:etl:[org section] Skipping column header row in org section, row=['Код', 'Описание', nan, 'Сума']
INFO:etl:[org section] Skipping column header row in org section, row=['Код', 'Описание', nan, 'Сума']
INFO:etl:[org section] Skipping column header row in org section, row=['Код', 'Описание', nan, 'Сума']
INFO:etl:[org section] Skipping column header row in org section, row=['Код', 'Описание', nan, 'Сума']
INFO:etl:[org section] Skipping column header row in org section, row=['Код', 'Описание', nan, 'Сума']
INFO:etl:[org section] Skipping column header row in org section, row=['Код', 'Описание', nan, 'Сума']
INFO:etl:[org section] Skipping column header row in org section, row=['Код', 'Описание', nan, 'Сума']
INFO:etl:[org section] Skipping column header row in org section, row=['Код', 'Описание', nan, 'Сума']
INFO:etl:[org section] Skipping column header row in org section, row=['Код', 'Описание', nan, 'Сума']
INFO:etl:[org section] Skipping column header row in org section, row=['Код', 'Описание', nan, 'Сума']
INFO:etl:[org section] Skipping column header row in org section, row=['Код', 'Описание', nan, 'Сума']
INFO:etl:[org section] Skipping column header row in org section, row=['Код', 'Описание', nan, 'Сума']
INFO:etl:[org section] Skipping column header row in org section, row=['Код', 'Описание', nan, 'Сума']
INFO:etl:[org section] Skipping column header row in org section, row=['Код', 'Описание', nan, 'Сума']
INFO:etl:[org section] Skipping column header row in org section, row=['Код', 'Описание', nan, 'Сума']
INFO:etl:[org section] Skipping column header row in org section, row=['Код', 'Описание', nan, 'Сума']
INFO:etl:[org section] Skipping column header row in org section, row=['Код', 'Описание', nan, 'Сума']
INFO:etl:[org section] Skipping column header row in org section, row=['Код', 'Описание', nan, 'Сума']
INFO:etl:[org section] Skipping column header row in org section, row=['Код', 'Описание', nan, 'Сума']
INFO:etl:[org section] Skipping column header row in org section, row=['Код', 'Описание', nan, 'Сума']
INFO:etl:[org section] Skipping column header row in org section, row=['Код', 'Описание', nan, 'Сума']
INFO:etl:[org section] Skipping column header row in org section, row=['Код', 'Описание', nan, 'Сума']
INFO:etl:[org section] Skipping column header row in org section, row=['Код', 'Описание', nan, 'Сума']
INFO:etl:[org section] Skipping column header row in org section, row=['Код', 'Описание', nan, 'Сума']
INFO:etl:[org section] Skipping column header row in org section, row=['Код', 'Описание', nan, 'Сума']
INFO:etl:[org section] Skipping column header row in org section, row=['Код', 'Описание', nan, 'Сума']
INFO:etl:[org section] Skipping column header row in org section, row=['Код', 'Описание', nan, 'Сума']
INFO:etl:[org section] Skipping column header row in org section, row=['Код', 'Описание', nan, 'Сума']

[ValidationResult(filename='SEBRA-09042026.xlsx', is_valid=True, is_summary_valid=True, are_sections_valid=True, is_summary_sum_equal_sum_of_sections=True, errors=[]),
 ValidationResult(filename='SEBRA-15052026.xlsx', is_valid=True, is_summary_valid=True, are_sections_valid=True, is_summary_sum_equal_sum_of_sections=True, errors=[]),
 ValidationResult(filename='SEBRA-27052026.xlsx', is_valid=True, is_summary_valid=True, are_sections_valid=True, is_summary_sum_equal_sum_of_sections=True, errors=[]),
 ValidationResult(filename='SEBRA-28052026.xlsx', is_valid=True, is_summary_valid=True, are_sections_valid=True, is_summary_sum_equal_sum_of_sections=True, errors=[])]

In [8]:
sebra_datas[1].summary.data

,start_date,end_date,operation_code,operation_description,currency,amount
0,15.05.2026,15.05.2026,01,"Заплати, възнаграждения и други плащания за пе...",EUR,7307203.01
1,15.05.2026,15.05.2026,02,Удържани данъци и осигурителни вноски от запла...,EUR,94518.42
2,15.05.2026,15.05.2026,03,Плащания за други удръжки от възнаграждения за...,EUR,22810.50
3,15.05.2026,15.05.2026,05,Осигурителни вноски за сметка на осигурителя,EUR,123620.77
4,15.05.2026,15.05.2026,10,Издръжка,EUR,37243781.99
5,15.05.2026,15.05.2026,18,Други разходи,EUR,157083.70
6,15.05.2026,15.05.2026,20,Разходи за лихви,EUR,52.50
7,15.05.2026,15.05.2026,30,Текущи субсидии за предприятия,EUR,824988.99
8,15.05.2026,15.05.2026,40,"Стипендии, пенсии, помощи и текущи трансфери з...",EUR,3898141.55
9,15.05.2026,15.05.2026,50,"Плащания за дълготрайни активи, основен ремонт...",EUR,2074313.20
10,15.05.2026,15.05.2026,60,Трансфери за бюджетни и извънбюджетни сметки,EUR,24282141.22
11,15.05.2026,15.05.2026,88,Средства на разпореждане,EUR,6591872.04
12,15.05.2026,15.05.2026,89,Друго финансиране,EUR,250720.56
13,15.05.2026,15.05.2026,90,Възстановени приходи,EUR,550667.85
14,15.05.2026,15.05.2026,91,Теглене на BGN в брой,EUR,9500
15,15.05.2026,15.05.2026,96,Преводи по нареждане на титуляра с други плате...,EUR,40959
16,15.05.2026,15.05.2026,98,Други операции в БНБ,EUR,-6654909.23
17,15.05.2026,15.05.2026,2974e36,Трансфери за местни дейности за общини,EUR,286949
18,15.05.2026,15.05.2026,55d283b,Обща субсидия за финансиране на делегираните о...,EUR,3791358
19,15.05.2026,15.05.2026,d8b5c4b,Трансфери за други целеви разходи за общини,EUR,1115347.06